package io.github.astrarre.transfer.v0.api.keys.generated;
// this class is autogenerated
// @formatter:off

import io.github.astrarre.transfer.v0.api.TransactionHandler;
import io.github.astrarre.transfer.v0.api.Key;
import io.github.astrarre.transfer.v0.api.Transaction;
import it.unimi.dsi.fastutil.%lower%s.%Upper%ArrayList;

public class %Upper%KeyImpl extends Key.%Upper% {
	private final TransactionHandler handler;
	private final %Upper%ArrayList values = new %Upper%ArrayList();

	public %Upper%KeyImpl(TransactionHandler handler, %lower% originalValue) {
		this.handler = handler;
		this.values.add(0, originalValue);
	}

	public %Upper%KeyImpl(%lower% originalValue) {this(new TransactionHandler(), originalValue);}

	@Override
	public %lower% get(Transaction transaction) {
		return this.values.top%Upper%();
	}

	@Override
	protected void onApply(Transaction transaction) {
		this.handler.pop(transaction);
		Transaction parent = transaction.getParent();
		this.set(parent, this.values.pop%Upper%());
	}

	@Override
	protected void onAbort(Transaction transaction) {
		this.values.pop%Upper%();
		this.handler.pop(transaction);
	}

	@Override
	public void set(Transaction transaction, %lower% val) {
		if (this.handler.store(transaction)) {
			this.values.set(this.values.size() - 1, val);
		} else {
			this.values.push(val);
			transaction.enlistKey(this);
		}
	}
}
